name: tepat_public_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.2.0
  bloc: ^7.0.0
  cloud_firestore: ^2.2.2
  dartz: ^0.9.2
  dio: ^4.0.0
  envify: ^2.0.0
  equatable: ^2.0.3
  file_picker: ^3.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^8.1.3
  flutter_bloc: ^7.0.1
  flutter_local_notifications: ^6.0.0
  flutter_secure_storage: ^4.2.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^0.14.2
  geolocator: ^7.2.0
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  heroicons: ^0.2.1
  image_picker: ^0.8.1+1
  injectable: ^1.4.1
  intl: ^0.17.0
  photo_view: ^0.11.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.0
  build_runner: ^2.0.5
  change_app_package_name: ^1.0.0
  envify_generator: ^2.0.0
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
