name: tepat_public_flutter

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        # run: flutter format --set-exit-if-changed lib test
        run: echo 'no format :D'

      - name: Analyze
        # run: flutter analyze lib test
        run: echo 'no analyze :D'

      - name: Run tests
        # run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        run: echo 'no test :D'

      - name: Check Code Coverage
        # uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        run: echo 'yes :D'

      - name: Build APK Debug
        run: flutter build apk --debug --flavor development --target lib/main_development.dart
