name: tepat_public_flutter

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        # run: flutter format --set-exit-if-changed lib test
        run: echo 'no format :D'

      - name: Analyze
        # run: flutter analyze lib test
        run: echo 'no analyze :D'

      - name: Run tests
        # run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        run: echo 'no test :D'

      - name: Check Code Coverage
        # uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        run: echo 'yes :D'

      - name: Build APK Debug
        run: flutter build apk --debug --flavor development --target lib/main_development.dart

      - name: Rename APK
        run: |
          last_commit_id=$(git rev-parse --short HEAD)
          cd build/app/outputs/flutter-apk/
          new_apk_name=app-development-debug-${last_commit_id}.apk
          mv app-development-debug.apk $new_apk_name
          # curl -F document=@"$new_apk_name" https://api.telegram.org/bot{{TELEGRAM_TOKEN}}/sendDocument?chat_id={{SKYNET_CHAT_ID}}
          # curl https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument?chat_id=${SKYNET_CHAT_ID}&document=$new_apk_name

      - name: Upload APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.SKYNET_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: send photo message
          document: build/app/outputs/flutter-apk/app-development-debug-$(git rev-parse --short HEAD).apk
